#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr -s 1920x1080 &
picom &
#nitrogen --restore &
${HOME}/.config/polybar/launch.sh
flameshot &
nm-applet &
variety &
 
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "Yubico Authenticator" desktop='^3' state=floating follow=on
bspc rule -a Galculator desktop='^3' state=floating follow=on
bspc rule -a Code desktop='^5' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Thunar desktop='^7' follow=on
bspc rule -a Pcmanfm desktop='^7' follow=on

